# Indexing and iteration

In [1]:
import numpy as np

In [3]:
array_a = np.array([3,4,5,6,7,202,11,240,1])
array_a

array([  3,   4,   5,   6,   7, 202,  11, 240,   1])

Get third element in the array

In [4]:
array_a[2]

5

Get first element in the array

In [5]:
array_a[0]

3

Get last element in the array 

In [6]:
array_a[-1]

1

Get next to last element in the array

In [7]:
array_a[-2]

240

Get all entries except for the first two

In [8]:
array_a[2:]

array([  5,   6,   7, 202,  11, 240,   1])

Get all entries except for the last three

In [9]:
array_a[:-3]

array([  3,   4,   5,   6,   7, 202])

Get every other entry

In [10]:
array_a[::2]

array([ 3,  5,  7, 11,  1])

In [11]:
array_a[0:len(array_a):2]

array([ 3,  5,  7, 11,  1])

Get every other entry starting in the second one

In [12]:
array_a[1:len(array_a):2]

array([  4,   6, 202, 240])

Changing array entries

In [13]:
array_a[2] = 10001
array_a

array([    3,     4, 10001,     6,     7,   202,    11,   240,     1])

In a 2D array (matrix)

In [14]:
array_b = np.array([[2,3,5], [35,1,5]])
array_b

array([[ 2,  3,  5],
       [35,  1,  5]])

In [15]:
array_b[1,2]

5

Same thing can be done with python lists

In [16]:
list_a = list(array_a)
list_a

[3, 4, 10001, 6, 7, 202, 11, 240, 1]

In [17]:
list_a[2]

10001

In [18]:
list_a[2] = 2000
list_a

[3, 4, 2000, 6, 7, 202, 11, 240, 1]

In [19]:
list_b = [[2,3,5], [35,1,5]]
list_b

[[2, 3, 5], [35, 1, 5]]

In [21]:
list_b[0][1]

3

### Arithmetic lists vs. summing arrays

In [32]:
list_a + list_a

[3, 4, 2000, 6, 7, 202, 11, 240, 1, 3, 4, 2000, 6, 7, 202, 11, 240, 1]

In [34]:
list_a * 2

[3, 4, 2000, 6, 7, 202, 11, 240, 1, 3, 4, 2000, 6, 7, 202, 11, 240, 1]

In [35]:
list_a * list_a

TypeError: can't multiply sequence by non-int of type 'list'

In [36]:
array_a + array_a

array([    6,     8, 20002,    12,    14,   404,    22,   480,     2])

In [37]:
array_a * 2

array([    6,     8, 20002,    12,    14,   404,    22,   480,     2])

In [38]:
array_a * array_a

array([        9,        16, 100020001,        36,        49,     40804,
             121,     57600,         1])

# Iteration

In [22]:
n = len(list_a)
n

9

### While loop

In [23]:
i = 0
while i < n:
    print(i, array_a[i], list_a[i])
    i = i + 1

0 3 3
1 4 4
2 10001 2000
3 6 6
4 7 7
5 202 202
6 11 11
7 240 240
8 1 1


In [24]:
i = 3
while i < n:
    print(i, array_a[i], list_a[i])
    i = i + 1

3 6 6
4 7 7
5 202 202
6 11 11
7 240 240
8 1 1


### For loop

In [25]:
for i in range(n):
    print(i, array_a[i], list_a[i])

0 3 3
1 4 4
2 10001 2000
3 6 6
4 7 7
5 202 202
6 11 11
7 240 240
8 1 1


In [27]:
list(range(n))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [28]:
for i in range(3, n):
    print(i, array_a[i], list_a[i])

3 6 6
4 7 7
5 202 202
6 11 11
7 240 240
8 1 1


In [29]:
list(range(3, n))

[3, 4, 5, 6, 7, 8]

In [41]:
new_list = []
for i in range(n):
    new_list.append(list_a[i] ** 2)

[9, 16, 4000000, 36, 49, 40804, 121, 57600, 1]

In [42]:
new_list

[9, 16, 4000000, 36, 49, 40804, 121, 57600, 1]

## Exercises

#### 1. Generate a new list that contains the elements of `list_a` multiplied by 10

#### 2. Multiply every element in * `list_b` by 3