# Selecting data

In [3]:
import numpy as np

In [5]:
x = np.array([4,5,6,24,63,1])
x

array([ 4,  5,  6, 24, 63,  1])

In [6]:
x > 10

array([False, False, False,  True,  True, False])

In [7]:
x[x > 10]

array([24, 63])

## Exercises

#### 1. Find  the odd and even numbers in the array above

Hint: x % 2 gives you the remainder of the division of x by 2